when@dev: &dev
    zenstruck_foundry:
        # La version 1 ne connait que cette option ici, pas de "persistence"
        auto_refresh_proxies: true

    # Configuration standard des services pour les tests
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\Factory\:
            resource: '%kernel.project_dir%/tests/Factory'

when@test: *dev
