<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRaIPJ7m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRaIPJ7m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRaIPJ7m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRaIPJ7m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRaIPJ7m\App_KernelDevDebugContainer([
    'container.build_hash' => 'RaIPJ7m',
    'container.build_id' => '1ec600eb',
    'container.build_time' => 1764624146,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRaIPJ7m');
